In [9]:
import numpy as np

In [10]:
X = np.array([[0, 2], [1, 1], [2, 0]])
X

array([[0, 2],
       [1, 1],
       [2, 0]])

In [11]:
X.T

array([[0, 1, 2],
       [2, 1, 0]])

In [12]:
np.cov(X)

array([[ 2.,  0., -2.],
       [ 0.,  0.,  0.],
       [-2.,  0.,  2.]])

In [13]:
np.cov(X.T)

array([[ 1., -1.],
       [-1.,  1.]])

In [14]:
X

array([[0, 2],
       [1, 1],
       [2, 0]])

In [17]:
x_mean = np.mean(X[:, 0])
x_mean

1.0

In [18]:
x_var = np.sum((X[:, 0] - x_mean)**2)
x_var

2.0

In [19]:
y_mean = np.mean(X[:,1])
y_mean

1.0

In [20]:
y_var = np.sum((X[:, 1] - y_mean) ** 2)
y_var

2.0

In [22]:
cov_xy = np.sum(np.dot(X[:, 0] - x_mean, X[:, 1] - y_mean))
cov_xy


-2.0

In [23]:
cov = np.stack(([x_var, cov_xy], [cov_xy, y_var]), axis = 0)
cov

array([[ 2., -2.],
       [-2.,  2.]])

In [24]:
np.cov(X.T)

array([[ 1., -1.],
       [-1.,  1.]])