In [1]:
import numpy as np
from numpy import linalg

In [2]:
A = np.array([[3, 0],
              [4, 5]])
linalg.svd(A)

(array([[-0.31622777, -0.9486833 ],
        [-0.9486833 ,  0.31622777]]),
 array([6.70820393, 2.23606798]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))