In [37]:
X = [
    [0, 1, 2],
    [1, 0, -1],
    [2, 3, 1]
]

In [38]:
import numpy as np

In [39]:
X = np.array(X)
X

array([[ 0,  1,  2],
       [ 1,  0, -1],
       [ 2,  3,  1]])

In [40]:
mean_c = np.mean(X, axis = 0)
mean_c

array([1.        , 1.33333333, 0.66666667])

In [41]:
SW = np.zeros((3, 3))
SW += (X - mean_c).T.dot(X - mean_c)
SW

array([[ 2.        ,  2.        , -1.        ],
       [ 2.        ,  4.66666667,  2.33333333],
       [-1.        ,  2.33333333,  4.66666667]])