In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn import linear_model

In [2]:
df = datasets.load_iris()
data = df.data
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [3]:
target = df.target
target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [5]:
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.25)
model = KNeighborsClassifier(n_neighbors = 3)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [6]:
y_predicted = model.predict(x_test)
y_predicted

array([2, 0, 1, 0, 0, 0, 2, 2, 2, 1, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 2, 1,
       0, 2, 1, 1, 2, 0, 1, 0, 1, 1, 0, 1, 0, 2, 1, 0])

In [7]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_predicted)
accuracy

0.9473684210526315

In [8]:
from sklearn.decomposition import PCA

In [9]:
pca = PCA(2)
x_projected = pca.fit_transform(data)
x_projected

array([[-2.68412563,  0.31939725],
       [-2.71414169, -0.17700123],
       [-2.88899057, -0.14494943],
       [-2.74534286, -0.31829898],
       [-2.72871654,  0.32675451],
       [-2.28085963,  0.74133045],
       [-2.82053775, -0.08946138],
       [-2.62614497,  0.16338496],
       [-2.88638273, -0.57831175],
       [-2.6727558 , -0.11377425],
       [-2.50694709,  0.6450689 ],
       [-2.61275523,  0.01472994],
       [-2.78610927, -0.235112  ],
       [-3.22380374, -0.51139459],
       [-2.64475039,  1.17876464],
       [-2.38603903,  1.33806233],
       [-2.62352788,  0.81067951],
       [-2.64829671,  0.31184914],
       [-2.19982032,  0.87283904],
       [-2.5879864 ,  0.51356031],
       [-2.31025622,  0.39134594],
       [-2.54370523,  0.43299606],
       [-3.21593942,  0.13346807],
       [-2.30273318,  0.09870885],
       [-2.35575405, -0.03728186],
       [-2.50666891, -0.14601688],
       [-2.46882007,  0.13095149],
       [-2.56231991,  0.36771886],
       [-2.63953472,

In [10]:
x1 = x_projected[:, 0]
x1

array([-2.68412563, -2.71414169, -2.88899057, -2.74534286, -2.72871654,
       -2.28085963, -2.82053775, -2.62614497, -2.88638273, -2.6727558 ,
       -2.50694709, -2.61275523, -2.78610927, -3.22380374, -2.64475039,
       -2.38603903, -2.62352788, -2.64829671, -2.19982032, -2.5879864 ,
       -2.31025622, -2.54370523, -3.21593942, -2.30273318, -2.35575405,
       -2.50666891, -2.46882007, -2.56231991, -2.63953472, -2.63198939,
       -2.58739848, -2.4099325 , -2.64886233, -2.59873675, -2.63692688,
       -2.86624165, -2.62523805, -2.80068412, -2.98050204, -2.59000631,
       -2.77010243, -2.84936871, -2.99740655, -2.40561449, -2.20948924,
       -2.71445143, -2.53814826, -2.83946217, -2.54308575, -2.70335978,
        1.28482569,  0.93248853,  1.46430232,  0.18331772,  1.08810326,
        0.64166908,  1.09506066, -0.74912267,  1.04413183, -0.0087454 ,
       -0.50784088,  0.51169856,  0.26497651,  0.98493451, -0.17392537,
        0.92786078,  0.66028376,  0.23610499,  0.94473373,  0.04

In [11]:
from matplotlib import pyplot as plt
import seaborn as sns

In [12]:
x = pd.DataFrame(data = data, columns = df.feature_names)
x.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [14]:
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.25, random_state = 1234)
x_train

array([[4.6, 3.6, 1. , 0.2],
       [5. , 2.3, 3.3, 1. ],
       [5.5, 3.5, 1.3, 0.2],
       [6.2, 2.2, 4.5, 1.5],
       [5.2, 4.1, 1.5, 0.1],
       [6.9, 3.1, 5.1, 2.3],
       [7.2, 3.2, 6. , 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [5.8, 2.8, 5.1, 2.4],
       [6.7, 3. , 5.2, 2.3],
       [7.7, 3. , 6.1, 2.3],
       [6.7, 3.1, 5.6, 2.4],
       [4.9, 3. , 1.4, 0.2],
       [6.5, 3. , 5.2, 2. ],
       [7.6, 3. , 6.6, 2.1],
       [6.2, 2.9, 4.3, 1.3],
       [4.9, 2.4, 3.3, 1. ],
       [5.6, 2.9, 3.6, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.6, 2.9, 4.6, 1.3],
       [5.1, 3.5, 1.4, 0.3],
       [5.1, 3.4, 1.5, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.7, 2.5, 5. , 2. ],
       [6.5, 3.2, 5.1, 2. ],
       [5.1, 3.7, 1.5, 0.4],
       [5.5, 4.2, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.6, 5.6, 1.4],
       [6.7, 3.3, 5.7, 2.5],
       [5.7, 2.8, 4.5, 1.3],
       [5. , 3

In [16]:
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.25, random_state = 1234)
x_train

array([[4.6, 3.6, 1. , 0.2],
       [5. , 2.3, 3.3, 1. ],
       [5.5, 3.5, 1.3, 0.2],
       [6.2, 2.2, 4.5, 1.5],
       [5.2, 4.1, 1.5, 0.1],
       [6.9, 3.1, 5.1, 2.3],
       [7.2, 3.2, 6. , 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [5.8, 2.8, 5.1, 2.4],
       [6.7, 3. , 5.2, 2.3],
       [7.7, 3. , 6.1, 2.3],
       [6.7, 3.1, 5.6, 2.4],
       [4.9, 3. , 1.4, 0.2],
       [6.5, 3. , 5.2, 2. ],
       [7.6, 3. , 6.6, 2.1],
       [6.2, 2.9, 4.3, 1.3],
       [4.9, 2.4, 3.3, 1. ],
       [5.6, 2.9, 3.6, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.6, 2.9, 4.6, 1.3],
       [5.1, 3.5, 1.4, 0.3],
       [5.1, 3.4, 1.5, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.7, 2.5, 5. , 2. ],
       [6.5, 3.2, 5.1, 2. ],
       [5.1, 3.7, 1.5, 0.4],
       [5.5, 4.2, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.6, 5.6, 1.4],
       [6.7, 3.3, 5.7, 2.5],
       [5.7, 2.8, 4.5, 1.3],
       [5. , 3

In [17]:
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.25, random_state = 1234)
x_train

array([[4.6, 3.6, 1. , 0.2],
       [5. , 2.3, 3.3, 1. ],
       [5.5, 3.5, 1.3, 0.2],
       [6.2, 2.2, 4.5, 1.5],
       [5.2, 4.1, 1.5, 0.1],
       [6.9, 3.1, 5.1, 2.3],
       [7.2, 3.2, 6. , 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [5.8, 2.8, 5.1, 2.4],
       [6.7, 3. , 5.2, 2.3],
       [7.7, 3. , 6.1, 2.3],
       [6.7, 3.1, 5.6, 2.4],
       [4.9, 3. , 1.4, 0.2],
       [6.5, 3. , 5.2, 2. ],
       [7.6, 3. , 6.6, 2.1],
       [6.2, 2.9, 4.3, 1.3],
       [4.9, 2.4, 3.3, 1. ],
       [5.6, 2.9, 3.6, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.6, 2.9, 4.6, 1.3],
       [5.1, 3.5, 1.4, 0.3],
       [5.1, 3.4, 1.5, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.7, 2.5, 5. , 2. ],
       [6.5, 3.2, 5.1, 2. ],
       [5.1, 3.7, 1.5, 0.4],
       [5.5, 4.2, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.6, 5.6, 1.4],
       [6.7, 3.3, 5.7, 2.5],
       [5.7, 2.8, 4.5, 1.3],
       [5. , 3

In [18]:
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.25)
x_train

array([[5.7, 2.5, 5. , 2. ],
       [5.9, 3.2, 4.8, 1.8],
       [6.2, 2.2, 4.5, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [5.6, 2.8, 4.9, 2. ],
       [5.9, 3. , 5.1, 1.8],
       [4.9, 2.5, 4.5, 1.7],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.5, 3. , 5.2, 2. ],
       [7.2, 3.2, 6. , 1.8],
       [6.5, 3.2, 5.1, 2. ],
       [5.3, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [6. , 2.2, 5. , 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [6.7, 3.1, 4.7, 1.5],
       [4.9, 3.1, 1.5, 0.1],
       [6.1, 3. , 4.6, 1.4],
       [5.5, 2.5, 4. , 1.3],
       [4.4, 3. , 1.3, 0.2],
       [6.3, 3.3, 4.7, 1.6],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [5.1, 3.7, 1.5, 0.4],
       [5.8, 2.8, 5.1, 2.4],
       [6.7, 2.5, 5.8, 1.8],
       [6.9, 3.1, 4.9, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.5, 3

In [19]:
x_train, x_test, y_train, y_test = train_test_split(data, target, test_size = 0.25, random_state = 1234)
x_train

array([[4.6, 3.6, 1. , 0.2],
       [5. , 2.3, 3.3, 1. ],
       [5.5, 3.5, 1.3, 0.2],
       [6.2, 2.2, 4.5, 1.5],
       [5.2, 4.1, 1.5, 0.1],
       [6.9, 3.1, 5.1, 2.3],
       [7.2, 3.2, 6. , 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [5.8, 2.8, 5.1, 2.4],
       [6.7, 3. , 5.2, 2.3],
       [7.7, 3. , 6.1, 2.3],
       [6.7, 3.1, 5.6, 2.4],
       [4.9, 3. , 1.4, 0.2],
       [6.5, 3. , 5.2, 2. ],
       [7.6, 3. , 6.6, 2.1],
       [6.2, 2.9, 4.3, 1.3],
       [4.9, 2.4, 3.3, 1. ],
       [5.6, 2.9, 3.6, 1.3],
       [5.6, 3. , 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [6.6, 2.9, 4.6, 1.3],
       [5.1, 3.5, 1.4, 0.3],
       [5.1, 3.4, 1.5, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [5.7, 2.5, 5. , 2. ],
       [6.5, 3.2, 5.1, 2. ],
       [5.1, 3.7, 1.5, 0.4],
       [5.5, 4.2, 1.4, 0.2],
       [5.1, 3.5, 1.4, 0.2],
       [6.3, 2.5, 5. , 1.9],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.6, 5.6, 1.4],
       [6.7, 3.3, 5.7, 2.5],
       [5.7, 2.8, 4.5, 1.3],
       [5. , 3